### ISSUE TITLE
New SDK Problems that I generated 

### ISSUE THREAD

**Issue by naeemAkee** [mapbox/ios-sdk-examples#357]
Hello Sir,

I'm using Mapbox SDK, and when installing new pods, It's pod will be showing errors.

I change pods and it showing error again and again.

I was using these pods,
    **pod 'Mapbox-iOS-SDK', '~> 5.1'
    pod 'MapboxNavigation', '~> 0.35.0'
    pod 'MapboxGeocoder.swift', '~> 0.11'**

I updated pods too
    **pod 'Mapbox-iOS-SDK', '~> 5.3'
    pod 'MapboxNavigation', '~> 0.37.0'
    pod 'MapboxGeocoder.swift', '~> 0.11'**

It showing post again and again.

<img width="595" alt="Screenshot 2019-09-19 at 9 55 31 PM" src="https://user-images.githubusercontent.com/43524143/65265033-666be580-db29-11e9-8e88-63c0dc9d26a2.png">

<img width="297" alt="Screenshot 2019-09-19 at 9 55 49 PM" src="https://user-images.githubusercontent.com/43524143/65265041-6cfa5d00-db29-11e9-92c3-67b8e88090d2.png">

**Comment by captainbarbosa** [comment]
Hi @naeemAkee — thanks for using Mapbox. This repo is for reporting bugs with examples, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions or help troubleshooting installation, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).

**Comment by naeemAkee** [comment]
@captainbarbosa  So you don't know the reason ? or have no solution of it ?

**Comment by captainbarbosa** [comment]
The issue could be caused by many reasons, but it is not possible to determine why without more information. We recommend verifying that all versions of the Pods you're trying to install are correct, your Podfile has [valid syntax](https://guides.cocoapods.org/syntax/podspec.html#specification), and your version of CocoaPods is [up to date](https://github.com/CocoaPods/CocoaPods/releases). If you continue to run into issues, please reach out to our support team to further troubleshoot.

**Comment by naeemAkee** [comment]
@captainbarbosa Thank you Ma'am

**Comment by naeemAkee** [comment]
@captainbarbosa  @friedbunny  can you please tell me the solution other then referring here and there.

**Comment by naeemAkee** [comment]
<img width="891" alt="Screenshot 2019-09-19 at 11 22 57 PM" src="https://user-images.githubusercontent.com/43524143/65270911-90c3a000-db35-11e9-8dae-48b3135111d1.png">

**Comment by captainbarbosa** [comment]
@naeemAkee The other issue was closed because we couldn't reproduce the issue using the specification you provided. As such, we've determined that this request is better suited for our support team who can assist in figuring out why you're unable to install via CocoaPods.

You can get in touch with out support team through our [contact form](https://support.mapbox.com/hc/en-us). When contacting our team, please provide the full Podspec file you're working with (if possible), and the version of CocoaPods you are using so our team can better assist you.
