### ISSUE TITLE
UIWebview Deprecated API Usage

### ISSUE THREAD

**Issue by samirMCS** [mapbox/ios-sdk-examples#373]
i had replace UIWebView to WKWebView. but still got warning form apple.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

so i am search using terminal commands:      _grep -r 'UIWebView' ._
i found UIWebView in mapbox
Binary file ./Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox matches

**Comment by captainbarbosa** [comment]
Hi @samirMCS - 

`.dSYM` files don't contain any functional code. This is debugging metadata that’s been stripped from the Mapbox framework. The reason why you've found this mention of `UIWebView` in our `dSYM` is because we link to UIKit and the version of iOS that may include `UIWebView`s.

`UIWebView`s don't exist in our actual framework though, which can be confirmed by running 
`nm /mapbox-gl-native-ios/build/ios/pkg/dynamic/Mapbox.framework/Mapbox | grep -i UIWebView`. This returns no results. Additionally, we ship a variety of internal apps to TestFlight and the App Store and haven't come across this warning ourselves.

If you're using other third-party frameworks within your app, you may want to confirm using `nm` that there are no other instances of `UIWebView` in your project.

(See https://github.com/mapbox/mapbox-gl-native/issues/15559#issuecomment-528128516 for a similar discussion).
